server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clubmileage?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

#  sql:
#    init:
#      mode: always

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true


  data:
    mongodb:
      host: localhost
      port: 27017
      database: clubmileage
      username: root
      password: root
      authentication-database: admin

logging:
  level:

    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
